# Project: Proyecto Estructura de Datos U3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../asignar_memoria.o ../cambiar_estado.o ../crear_proceso.o ../ejecutar_cpu.o ../liberar_memoria.o ../main.o ../ver_bloqueados.o ../ver_procesos.o
LINKOBJ  = ../asignar_memoria.o ../cambiar_estado.o ../crear_proceso.o ../ejecutar_cpu.o ../liberar_memoria.o ../main.o ../ver_bloqueados.o ../ver_procesos.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Proyecto Estructura de Datos U3.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../asignar_memoria.o: ../asignar_memoria.cpp
	$(CPP) -c ../asignar_memoria.cpp -o ../asignar_memoria.o $(CXXFLAGS)

../cambiar_estado.o: ../cambiar_estado.cpp
	$(CPP) -c ../cambiar_estado.cpp -o ../cambiar_estado.o $(CXXFLAGS)

../crear_proceso.o: ../crear_proceso.cpp
	$(CPP) -c ../crear_proceso.cpp -o ../crear_proceso.o $(CXXFLAGS)

../ejecutar_cpu.o: ../ejecutar_cpu.cpp
	$(CPP) -c ../ejecutar_cpu.cpp -o ../ejecutar_cpu.o $(CXXFLAGS)

../liberar_memoria.o: ../liberar_memoria.cpp
	$(CPP) -c ../liberar_memoria.cpp -o ../liberar_memoria.o $(CXXFLAGS)

../main.o: ../main.cpp
	$(CPP) -c ../main.cpp -o ../main.o $(CXXFLAGS)

../ver_bloqueados.o: ../ver_bloqueados.cpp
	$(CPP) -c ../ver_bloqueados.cpp -o ../ver_bloqueados.o $(CXXFLAGS)

../ver_procesos.o: ../ver_procesos.cpp
	$(CPP) -c ../ver_procesos.cpp -o ../ver_procesos.o $(CXXFLAGS)
